// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAzyxWJEuCwW20njLIPOnxsvdWSpMn1G4',
    appId: '1:169264270155:web:d02774ee205c4231ffb6ce',
    messagingSenderId: '169264270155',
    projectId: 'flutterchatapp-3ed50',
    authDomain: 'flutterchatapp-3ed50.firebaseapp.com',
    storageBucket: 'flutterchatapp-3ed50.appspot.com',
    measurementId: 'G-811ECM2SXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEnPJcmek2b2XO9iGYH7QKU27w8qJ4d2A',
    appId: '1:169264270155:android:f89be006abfb36bcffb6ce',
    messagingSenderId: '169264270155',
    projectId: 'flutterchatapp-3ed50',
    storageBucket: 'flutterchatapp-3ed50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpDbHfQi69ETXO2d36kFNt4B-uRKOQUH0',
    appId: '1:169264270155:ios:8f31f3230f90b4ebffb6ce',
    messagingSenderId: '169264270155',
    projectId: 'flutterchatapp-3ed50',
    storageBucket: 'flutterchatapp-3ed50.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpDbHfQi69ETXO2d36kFNt4B-uRKOQUH0',
    appId: '1:169264270155:ios:8f31f3230f90b4ebffb6ce',
    messagingSenderId: '169264270155',
    projectId: 'flutterchatapp-3ed50',
    storageBucket: 'flutterchatapp-3ed50.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAzyxWJEuCwW20njLIPOnxsvdWSpMn1G4',
    appId: '1:169264270155:web:3b50e577633e217effb6ce',
    messagingSenderId: '169264270155',
    projectId: 'flutterchatapp-3ed50',
    authDomain: 'flutterchatapp-3ed50.firebaseapp.com',
    storageBucket: 'flutterchatapp-3ed50.appspot.com',
    measurementId: 'G-XSR8B9GZRG',
  );
}
